# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0035_auto_20190530_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatarget',
            options={'verbose_name': 'SEA\u9884\u6d4b\u7ed3\u679c', 'verbose_name_plural': 'SEA\u9884\u6d4b\u7ed3\u679c'},
        ),
    ]
