# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0037_auto_20190531_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='reference_file',
            field=models.FileField(null=True, upload_to=works.models.dock_upload_to, verbose_name='reference_file'),
        ),
    ]
