# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-31 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0038_auto_20190531_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock',
            name='email',
            field=models.CharField(max_length=100, verbose_name='email'),
        ),
    ]
